{"uid":"ef4c55a7e047a067","name":"test_NAF_3_4_0_modify_name","fullName":"tests.android.test_3_Account_Setup.TestPersonInformationManagement#test_NAF_3_4_0_modify_name","historyId":"07dd972455b45187e54f644928e643fe","time":{"start":1753461681552,"stop":1753461681552,"duration":0},"description":"\n    Test Case: NAF-55\n    As a registered user I can view and update my profile settings\n    Scenario: Modify Name\n    \n    Steps:\n    1. Open the app, assume the user is logged in\n    2. Go to \"My Profile\" button\n    3. Click on \"Edit\" button\n    4. Enter name\n    5. Click on \"Save\" button\n    ","descriptionHtml":"<pre><code>Test Case: NAF-55\nAs a registered user I can view and update my profile settings\nScenario: Modify Name\n\nSteps:\n1. Open the app, assume the user is logged in\n2. Go to &quot;My Profile&quot; button\n3. Click on &quot;Edit&quot; button\n4. Enter name\n5. Click on &quot;Save&quot; button\n</code></pre>\n","status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/qingqinfang/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp\\:8203 tcp\\:6790' exited with code 1'; Command output: adb: error: more than one device/emulator\n\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/qingqinfang/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp\\:8203 tcp\\:6790' exited with code 1'; Command output: adb: error: more than one device/emulator\n\n    at getResponseForW3CError (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1143:9)\n    at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:487:57)","statusTrace":"tests/android/test_3_Account_Setup.py:34: in setup_and_teardown\n    driver = DriverManagerAndroid.get_driver()\ncore/driver_manager_android.py:20: in get_driver\n    cls._driver = cls._create_driver()\ncore/driver_manager_android.py:51: in _create_driver\n    driver = webdriver.Remote(Config.APPIUM_SERVER_URL, options=options)\nvenv/lib/python3.13/site-packages/appium/webdriver/webdriver.py:229: in __init__\n    super().__init__(\nvenv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:208: in __init__\n    self.start_session(capabilities)\nvenv/lib/python3.13/site-packages/appium/webdriver/webdriver.py:321: in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\nvenv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:347: in execute\n    self.error_handler.check_response(response)\nvenv/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/qingqinfang/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp\\:8203 tcp\\:6790' exited with code 1'; Command output: adb: error: more than one device/emulator\nE   \nE   Stacktrace:\nE   UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/qingqinfang/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp\\:8203 tcp\\:6790' exited with code 1'; Command output: adb: error: more than one device/emulator\nE   \nE       at getResponseForW3CError (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1143:9)\nE       at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:487:57)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"setup_and_teardown_test","time":{"start":1753461681553,"stop":1753461681553,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"setup_and_teardown","time":{"start":1753461681553,"stop":1753461682868,"duration":1315},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/qingqinfang/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp\\:8203 tcp\\:6790' exited with code 1'; Command output: adb: error: more than one device/emulator\n\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/qingqinfang/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp\\:8203 tcp\\:6790' exited with code 1'; Command output: adb: error: more than one device/emulator\n\n    at getResponseForW3CError (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1143:9)\n    at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:487:57)\n","statusTrace":"  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ~~~~~~~~~~~~~~~~~^^\n  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/venv/lib/python3.13/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/tests/android/test_3_Account_Setup.py\", line 34, in setup_and_teardown\n    driver = DriverManagerAndroid.get_driver()\n  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/core/driver_manager_android.py\", line 20, in get_driver\n    cls._driver = cls._create_driver()\n                  ~~~~~~~~~~~~~~~~~~^^\n  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/core/driver_manager_android.py\", line 51, in _create_driver\n    driver = webdriver.Remote(Config.APPIUM_SERVER_URL, options=options)\n  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/venv/lib/python3.13/site-packages/appium/webdriver/webdriver.py\", line 229, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        command_executor=command_executor,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        options=options,\n        ^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/venv/lib/python3.13/site-packages/appium/webdriver/webdriver.py\", line 321, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/Users/qingqinfang/Desktop/topfight/NancyAndersonFit/natal_mobile_auto/venv/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[{"name":"setup_and_teardown_test::0","time":{"start":1753461682895,"stop":1753461682895,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"epic","value":"Mobile App Testing-Android"},{"name":"story","value":"3.4.0 As a registered user I can view and update my profile settings"},{"name":"feature","value":"3.0.0 Account Setup"},{"name":"severity","value":"blocker"},{"name":"tag","value":"login"},{"name":"tag","value":"personal"},{"name":"tag","value":"order(2)"},{"name":"parentSuite","value":"tests.android"},{"name":"suite","value":"test_3_Account_Setup"},{"name":"subSuite","value":"TestPersonInformationManagement"},{"name":"host","value":"fqqqqq.local"},{"name":"thread","value":"4756-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.android.test_3_Account_Setup"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":["order(2)","personal","login"]},"source":"ef4c55a7e047a067.json","parameterValues":[]}